/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElM: typeof import('element-plus/es')['ElM']
  const ElMen: (typeof import('element-plus/es'))['ElMen']
  const ElMenu: (typeof import('element-plus/es'))['ElMenu']
  const ElNotificatio: (typeof import('element-plus/es'))['ElNotificatio']
}
